version: "3"

services:
  python:
    build: .
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    image: test_django
    container_name: test_django_container
    command: "python3 my_site/manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
    restart: always